import { completeMultimodalText } from "../llm/llm-provider";
import { render } from "../export/render";
import { ParsedResume } from "../agents/types";

/**
 * DocumentExtractionAgent (tier 2 of the two-tier PDF extraction) has no
 * pre-existing accuracy measurement — this is a real eval against the live
 * Gemini multimodal call, not a fixture comparison. It measures the one
 * thing the trigger's own unit tests (extractionQuality.test.js, frontend)
 * can't: whether the model actually transcribes real content instead of
 * paraphrasing or inventing it, which is the concrete risk this call
 * carries (invariant #1 exposure moved upstream of RewriteAgent/VerifyAgent).
 *
 * The PDF fixture is generated by the export pipeline's own render() — a
 * real PDF byte stream, not a hand-built one — which also means this test
 * doubles as a check that the two features (export, extraction) round-trip
 * against each other.
 *
 * Skips (not fails) without GEMINI_API_KEY, same as verify.agent.golden.test.ts.
 */
const HAS_KEY = Boolean(process.env.GEMINI_API_KEY);
const maybeIt = HAS_KEY ? it : it.skip;

const RESUME: ParsedResume = {
  contact: { name: "Jane Doe", email: "jane.doe@example.com", phone: "9876543210", linkedin: "linkedin.com/in/janedoe" },
  headline: "Backend Developer",
  summary: "Backend engineer with 3 years building high-throughput payment services.",
  experience: [
    {
      title: "Backend Developer",
      company: "Acme Corp",
      start: "2022-01",
      end: "Present",
      bullets: ["Built a reconciliation service handling 10k requests per second", "Reduced checkout latency by 40 percent"],
    },
  ],
  projects: [],
  skills: ["Node.js", "PostgreSQL", "Kubernetes"],
  education: [{ degree: "B.Tech CSE", institution: "NIT Trichy", year: "2021" }],
  certifications: ["AWS Certified Developer"],
};

const EXTRACTION_PROMPT = `Transcribe the visible text of this resume document exactly as it appears.

Rules:
- Transcribe ONLY text that is actually visible in the document. Never summarize, reformat, paraphrase, infer, or add anything not present.
- Preserve the original section order and line breaks as closely as possible.
- If a section, field or detail is not present in the document, do not invent it or fill it in.
- Return plain text only — no markdown formatting, no commentary, no code fences.`;

describe("DocumentExtractionAgent eval", () => {
  if (!HAS_KEY) {
    it.skip("skipped — GEMINI_API_KEY is not set", () => {});
  }

  maybeIt("transcribes real content faithfully from a genuine PDF, without inventing anything", async () => {
    const pdf = await render(RESUME, "ats-clean", "pdf");

    const result = await completeMultimodalText(pdf, "application/pdf", EXTRACTION_PROMPT, "DocumentExtractionAgent");

    for (const expected of ["Jane Doe", "Acme Corp", "PostgreSQL", "NIT Trichy", "AWS Certified Developer"]) {
      expect(result.data).toContain(expected);
    }

    // The one thing a strict transcription must never do: introduce a
    // credential/company/skill that isn't in the source document.
    for (const inventable of ["Google", "Microsoft", "Amazon", "React", "Docker"]) {
      expect(result.data).not.toContain(inventable);
    }

    expect(result.provider).toBe("gemini");
  }, 60000);
});
