import React, { useState } from "react";
import { Check, X, AlertTriangle, ArrowRight, Lock } from "lucide-react";
import {
  Card, Button, Chip, ScoreRing, SourceBadge, ConfidenceMark, LockedBlock, ICON,
  Field, Input, Checkbox,
} from "../../../design-system";
import { VerdictBanner } from "./shared/VerdictBanner";

/**
 * Overview — the first thing anyone sees, and the answer to four
 * questions in order: how did I do, what is working, what is hurting
 * me, what do I fix first.
 *
 * Nothing here is generated by this component. Strengths and problems
 * are the backend's own `reason` strings re-presented; the ranked fixes
 * are RoadmapAgent's, with its gain and confidence attached.
 */

function Finding({ tone, text, meta, source }) {
  const Icon = tone === "critical" ? X : tone === "warn" ? AlertTriangle : Check;
  return (
    <li className={`finding finding--${tone}`}>
      <Icon size={ICON.sm} strokeWidth={2} className="finding__icon" aria-hidden="true" />
      <div className="finding__body">
        <span className="finding__text">{text}</span>
        {meta ? <span className="finding__meta">{meta}</span> : null}
      </div>
      {source ? <SourceBadge source={source} /> : null}
    </li>
  );
}

/**
 * ConfirmGate — spec §2.2. Missing must-haves are never auto-counted
 * toward the projected score; only what the candidate ticks here does.
 * Un-ticked must-haves stay hard blockers on the verdict (§3).
 */
function ConfirmGate({ data, onConfirm }) {
  const criticalMissing = data.keywords.missing.filter((m) => m.priority === "critical");
  const showLinkedin = !data.contact?.linkedin;
  const showGithub = !data.contact?.github;
  const [checked, setChecked] = useState(() => new Set(criticalMissing.filter((m) => m.confirmed).map((m) => m.term)));
  const [linkedin, setLinkedin] = useState("");
  const [github, setGithub] = useState("");
  const [saving, setSaving] = useState(false);

  if (!criticalMissing.length && !showLinkedin && !showGithub) return null;

  function toggle(term) {
    setChecked((prev) => {
      const next = new Set(prev);
      next.has(term) ? next.delete(term) : next.add(term);
      return next;
    });
  }

  async function submit() {
    setSaving(true);
    try {
      await onConfirm({
        skills: Array.from(checked),
        contact: {
          linkedin: linkedin.trim() || undefined,
          github: github.trim() || undefined,
        },
      });
    } finally {
      setSaving(false);
    }
  }

  return (
    <Card pad="lg" className="confirm-gate">
      <div className="ds-label">The JD asks for these — tick the ones you actually have</div>
      <p className="ds-caption" style={{ marginTop: 4 }}>
        Only confirmed items count toward your projected score. We never assume you have a skill you haven't told us about.
      </p>

      {criticalMissing.length ? (
        <div className="confirm-gate__list">
          {criticalMissing.map((m) => (
            <Checkbox
              key={m.term}
              label={m.term}
              checked={checked.has(m.term)}
              onChange={() => toggle(m.term)}
            />
          ))}
        </div>
      ) : null}

      {(showLinkedin || showGithub) ? (
        <div className="confirm-gate__contact">
          {showLinkedin ? (
            <Field label="LinkedIn URL" hint="optional">
              {(a) => <Input value={linkedin} onChange={(e) => setLinkedin(e.target.value)} placeholder="linkedin.com/in/…" {...a} />}
            </Field>
          ) : null}
          {showGithub ? (
            <Field label="GitHub URL" hint="optional">
              {(a) => <Input value={github} onChange={(e) => setGithub(e.target.value)} placeholder="github.com/…" {...a} />}
            </Field>
          ) : null}
        </div>
      ) : null}

      <Button size="sm" variant="secondary" onClick={submit} loading={saving}>
        Update my projected score
      </Button>
    </Card>
  );
}

export function OverviewPanel({ data, onFix, onSeeAll, onConfirm }) {
  const topFixes = data.roadmap.filter((r) => !r.locked);

  return (
    <div className="report__stack">
      <VerdictBanner verdict={data.verdict} />
      <ConfirmGate data={data} onConfirm={onConfirm} />

      {/* ---------- score + rings ---------- */}
      <Card pad="lg">
        <div className="overview__head">
          <div className="overview__rings">
            <ScoreRing value={data.generic} label="Match" />
            <ScoreRing value={data.naukri} label="Portal" />
            {data.qualityScore != null
              ? <ScoreRing value={data.qualityScore} label="Quality" />
              : null}
          </div>

          <div className="overview__verdict">
            <div className="ds-h2">{data.scoreLabel}</div>
            <p className="ds-body overview__verdict-text">
              {data.fit.seniority || "Scored against this posting's requirements."}
            </p>
            <div className="overview__chips">
              <Chip tone="muted">{data.tier}</Chip>
              {data.fresherMode ? <Chip tone="muted">Fresher mode</Chip> : null}
              <Chip tone="muted">Exact {data.exactMatch}% · Semantic {data.semanticMatch}%</Chip>
            </div>
          </div>
        </div>

        {/* The portal gap — the India-specific insight, and the one
            number a competitor cannot copy. Tone follows the sign. */}
        {data.gapReason ? (
          <div className={`overview__gap overview__gap--${data.portalGap > 0 ? "weak" : data.portalGap < 0 ? "good" : "even"}`}>
            <div className="overview__gap-head">
              <span className="overview__gap-delta">
                {data.portalGap === 0 ? "±0" : `${data.portalGap > 0 ? "−" : "+"}${Math.abs(data.portalGap)}`}
              </span>
              <span className="ds-h3">
                {data.portalGap > 0
                  ? "points weaker on Naukri"
                  : data.portalGap < 0
                    ? "points stronger on Naukri"
                    : "the same on Naukri"}
              </span>
              <SourceBadge source="llm" />
            </div>
            <p className="ds-body-sm overview__gap-reason">{data.gapReason}</p>
          </div>
        ) : null}
      </Card>

      {/* ---------- working / hurting ---------- */}
      <div className="overview__split">
        <Card pad="lg">
          <div className="ds-label ds-good">What is working</div>
          {data.strengths.length ? (
            <ul className="finding-list">
              {data.strengths.map((s, i) => <Finding key={i} tone="good" {...s} />)}
            </ul>
          ) : (
            <p className="ds-body-sm" style={{ color: "var(--ink-mute)", marginTop: 8 }}>
              Nothing scored above 80% of its category. The fixes below are where to start.
            </p>
          )}
        </Card>

        <Card pad="lg">
          <div className="ds-label ds-critical">What is hurting you</div>
          {data.problems.length ? (
            <ul className="finding-list">
              {data.problems.map((p, i) => <Finding key={i} {...p} />)}
            </ul>
          ) : (
            <p className="ds-body-sm" style={{ color: "var(--ink-mute)", marginTop: 8 }}>
              No category fell below half marks. Look at the roadmap for smaller gains.
            </p>
          )}
        </Card>
      </div>

      {/* ---------- fix first ---------- */}
      <Card pad="lg">
        <div className="overview__fixhead">
          <div className="ds-label">Fix these first</div>
          <span className="ds-caption">Ranked by what each is worth</span>
        </div>

        <ol className="fixlist">
          {topFixes.map((r) => (
            <li key={r.rank} className="fixlist__item">
              <span className="fixlist__rank">{String(r.rank).padStart(2, "0")}</span>
              <div className="fixlist__body">
                <div className="ds-body">{r.fix}</div>
                {r.evidence ? <div className="ds-caption">{r.evidence}</div> : null}
              </div>
              <div className="fixlist__gain">
                <span className="ds-data ds-good">≈ +{r.gain}</span>
                <ConfidenceMark conf={r.conf} />
              </div>
            </li>
          ))}
        </ol>

        {data.lockedCount > 0 ? (
          <LockedBlock
            count={data.lockedCount}
            valueHint={data.lockedGain > 0 ? `+${data.lockedGain} points` : undefined}
            onUnlock={onSeeAll}
          />
        ) : null}

        <div className="overview__cta">
          <Button size="lg" onClick={onFix} iconRight={<ArrowRight size={ICON.sm} strokeWidth={ICON.stroke} />}>
            Fix my resume
          </Button>
          <span className="ds-caption">
            We rewrite the fixes above, show you every change, and re-score it.
          </span>
        </div>
      </Card>
    </div>
  );
}
